// <auto-generated />
using LibraryBookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryBookAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240826085754_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AuthorFirstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AuthorLastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AvailableForLoan")
                        .HasColumnType("bit");

                    b.Property<int>("BookGenre")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearOfPublication")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorFirstname = "Simon",
                            AuthorLastname = "Grenlang",
                            AvailableForLoan = false,
                            BookGenre = 5,
                            BookName = "Kalla Kårar Fotografen",
                            YearOfPublication = 1995
                        },
                        new
                        {
                            ID = 2,
                            AuthorFirstname = "Anna",
                            AuthorLastname = "Berg",
                            AvailableForLoan = true,
                            BookGenre = 6,
                            BookName = "Mörkrets Hjärta",
                            YearOfPublication = 2001
                        },
                        new
                        {
                            ID = 3,
                            AuthorFirstname = "Erik",
                            AuthorLastname = "Lund",
                            AvailableForLoan = true,
                            BookGenre = 7,
                            BookName = "Stjärnornas Krig",
                            YearOfPublication = 2010
                        },
                        new
                        {
                            ID = 4,
                            AuthorFirstname = "Maria",
                            AuthorLastname = "Nilsson",
                            AvailableForLoan = false,
                            BookGenre = 1,
                            BookName = "Historien om Oss",
                            YearOfPublication = 1998
                        },
                        new
                        {
                            ID = 5,
                            AuthorFirstname = "Lars",
                            AuthorLastname = "Johansson",
                            AvailableForLoan = true,
                            BookGenre = 2,
                            BookName = "Den Förlorade Staden",
                            YearOfPublication = 2005
                        },
                        new
                        {
                            ID = 6,
                            AuthorFirstname = "Karin",
                            AuthorLastname = "Svensson",
                            AvailableForLoan = false,
                            BookGenre = 6,
                            BookName = "Skräckens Hus",
                            YearOfPublication = 2012
                        },
                        new
                        {
                            ID = 7,
                            AuthorFirstname = "Olof",
                            AuthorLastname = "Andersson",
                            AvailableForLoan = true,
                            BookGenre = 7,
                            BookName = "Rymdens Hjältar",
                            YearOfPublication = 2018
                        },
                        new
                        {
                            ID = 8,
                            AuthorFirstname = "Eva",
                            AuthorLastname = "Karlsson",
                            AvailableForLoan = true,
                            BookGenre = 4,
                            BookName = "Livets Poesi",
                            YearOfPublication = 1993
                        },
                        new
                        {
                            ID = 9,
                            AuthorFirstname = "Per",
                            AuthorLastname = "Eriksson",
                            AvailableForLoan = false,
                            BookGenre = 5,
                            BookName = "Barnens Äventyr",
                            YearOfPublication = 2000
                        },
                        new
                        {
                            ID = 10,
                            AuthorFirstname = "Sofia",
                            AuthorLastname = "Larsson",
                            AvailableForLoan = true,
                            BookGenre = 9,
                            BookName = "Konstens Mästare",
                            YearOfPublication = 2015
                        },
                        new
                        {
                            ID = 11,
                            AuthorFirstname = "Gustav",
                            AuthorLastname = "Pettersson",
                            AvailableForLoan = false,
                            BookGenre = 8,
                            BookName = "Samhällets Spegel",
                            YearOfPublication = 1997
                        },
                        new
                        {
                            ID = 12,
                            AuthorFirstname = "Helena",
                            AuthorLastname = "Olsson",
                            AvailableForLoan = true,
                            BookGenre = 7,
                            BookName = "Fantasins Värld",
                            YearOfPublication = 2003
                        },
                        new
                        {
                            ID = 13,
                            AuthorFirstname = "Fredrik",
                            AuthorLastname = "Lind",
                            AvailableForLoan = false,
                            BookGenre = 6,
                            BookName = "Brott och Straff",
                            YearOfPublication = 2011
                        },
                        new
                        {
                            ID = 14,
                            AuthorFirstname = "Ingrid",
                            AuthorLastname = "Bengtsson",
                            AvailableForLoan = true,
                            BookGenre = 2,
                            BookName = "Historiska Hjältar",
                            YearOfPublication = 2007
                        },
                        new
                        {
                            ID = 15,
                            AuthorFirstname = "Henrik",
                            AuthorLastname = "Gustafsson",
                            AvailableForLoan = true,
                            BookGenre = 1,
                            BookName = "Livets Resa",
                            YearOfPublication = 1999
                        },
                        new
                        {
                            ID = 16,
                            AuthorFirstname = "Linda",
                            AuthorLastname = "Holm",
                            AvailableForLoan = false,
                            BookGenre = 6,
                            BookName = "Skräckens Natt",
                            YearOfPublication = 2013
                        },
                        new
                        {
                            ID = 17,
                            AuthorFirstname = "Johan",
                            AuthorLastname = "Sandberg",
                            AvailableForLoan = true,
                            BookGenre = 7,
                            BookName = "Rymdens Mysterier",
                            YearOfPublication = 2019
                        },
                        new
                        {
                            ID = 18,
                            AuthorFirstname = "Annika",
                            AuthorLastname = "Lundberg",
                            AvailableForLoan = true,
                            BookGenre = 4,
                            BookName = "Poesins Kraft",
                            YearOfPublication = 1994
                        },
                        new
                        {
                            ID = 19,
                            AuthorFirstname = "Mats",
                            AuthorLastname = "Hansson",
                            AvailableForLoan = false,
                            BookGenre = 5,
                            BookName = "Barnens Drömmar",
                            YearOfPublication = 2001
                        },
                        new
                        {
                            ID = 20,
                            AuthorFirstname = "Elin",
                            AuthorLastname = "Söderberg",
                            AvailableForLoan = true,
                            BookGenre = 9,
                            BookName = "Konstens Historia",
                            YearOfPublication = 2016
                        },
                        new
                        {
                            ID = 21,
                            AuthorFirstname = "Nils",
                            AuthorLastname = "Bergström",
                            AvailableForLoan = false,
                            BookGenre = 8,
                            BookName = "Samhällets Utveckling",
                            YearOfPublication = 1998
                        },
                        new
                        {
                            ID = 22,
                            AuthorFirstname = "Kristina",
                            AuthorLastname = "Ek",
                            AvailableForLoan = true,
                            BookGenre = 7,
                            BookName = "Fantasins Gränser",
                            YearOfPublication = 2004
                        },
                        new
                        {
                            ID = 23,
                            AuthorFirstname = "Anders",
                            AuthorLastname = "Lindgren",
                            AvailableForLoan = false,
                            BookGenre = 6,
                            BookName = "Brottets Skugga",
                            YearOfPublication = 2012
                        },
                        new
                        {
                            ID = 24,
                            AuthorFirstname = "Monica",
                            AuthorLastname = "Sjöberg",
                            AvailableForLoan = true,
                            BookGenre = 2,
                            BookName = "Historiska Äventyr",
                            YearOfPublication = 2008
                        },
                        new
                        {
                            ID = 25,
                            AuthorFirstname = "Tommy",
                            AuthorLastname = "Hedlund",
                            AvailableForLoan = true,
                            BookGenre = 1,
                            BookName = "Livets Berättelser",
                            YearOfPublication = 2000
                        },
                        new
                        {
                            ID = 26,
                            AuthorFirstname = "Ulla",
                            AuthorLastname = "Forsberg",
                            AvailableForLoan = false,
                            BookGenre = 6,
                            BookName = "Skräckens Tid",
                            YearOfPublication = 2014
                        },
                        new
                        {
                            ID = 27,
                            AuthorFirstname = "Patrik",
                            AuthorLastname = "Lindqvist",
                            AvailableForLoan = true,
                            BookGenre = 7,
                            BookName = "Rymdens Hemligheter",
                            YearOfPublication = 2020
                        },
                        new
                        {
                            ID = 28,
                            AuthorFirstname = "Birgitta",
                            AuthorLastname = "Nyström",
                            AvailableForLoan = true,
                            BookGenre = 4,
                            BookName = "Poesins Skönhet",
                            YearOfPublication = 1995
                        },
                        new
                        {
                            ID = 29,
                            AuthorFirstname = "Oskar",
                            AuthorLastname = "Sundström",
                            AvailableForLoan = false,
                            BookGenre = 5,
                            BookName = "Barnens Fantasi",
                            YearOfPublication = 2002
                        },
                        new
                        {
                            ID = 30,
                            AuthorFirstname = "Margareta",
                            AuthorLastname = "Lindholm",
                            AvailableForLoan = true,
                            BookGenre = 9,
                            BookName = "Konstens Under",
                            YearOfPublication = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
